# Docker Swarm stack for BacklogBox production deployment.
# Deploy: docker stack deploy -c docker-stack.yml backlogbox
#
# The CD workflow overrides the tag via `docker service update --image`,
# but the initial stack deploy needs a pullable image reference.

configs:
  caddyfile:
    file: ./Caddyfile

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  app:
    image: ghcr.io/backloxbox/backlogbox-app:latest
    secrets:
      - DATABASE_URL
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - TRUSTED_ORIGINS
      - ORIGIN
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - TMDB_API_KEY
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - POLAR_ACCESS_TOKEN
      - POLAR_PRODUCT_ID_MONTHLY
      - POLAR_PRODUCT_ID_YEARLY
      - POLAR_WEBHOOK_SECRET
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
      PROTOCOL_HEADER: 'x-forwarded-proto'
      HOST_HEADER: 'x-forwarded-host'
    networks:
      - app_network
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  DATABASE_URL:
    external: true
  BETTER_AUTH_SECRET:
    external: true
  BETTER_AUTH_URL:
    external: true
  TRUSTED_ORIGINS:
    external: true
  ORIGIN:
    external: true
  GITHUB_CLIENT_ID:
    external: true
  GITHUB_CLIENT_SECRET:
    external: true
  TMDB_API_KEY:
    external: true
  TWITCH_CLIENT_ID:
    external: true
  TWITCH_CLIENT_SECRET:
    external: true
  POLAR_ACCESS_TOKEN:
    external: true
  POLAR_PRODUCT_ID_MONTHLY:
    external: true
  POLAR_PRODUCT_ID_YEARLY:
    external: true
  POLAR_WEBHOOK_SECRET:
    external: true

networks:
  app_network:
    driver: overlay

volumes:
  caddy_data:
  caddy_config:
